### ISSUE TITLE
Top new repos moved to the bottom

### ISSUE THREAD

**Issue by necenzurat** [thechangelog/nightly#22]
Who had the idea to move the best part of the email to the bottom? 
At first i tought it was deja-vu. 
Please put top new repos first.

**Comment by jerodsanto** [comment]
@necenzurat you're in the minority on this one. Everyone else we've spoken with (ourselves included) prefer Top Starred to come first.

**Comment by sesh** [comment]
I'm with @necenzurat on this one – the primary reason I subscribed to Changelog Nightly is to see the top repositories from the day before. To me that's far more interesting since, for the most part, the Top Starred is very similar to what you can get from /trending.

(not that the switch will cause me to unsubscribe, just that my preference is how it was before)

**Comment by jerodsanto** [comment]
@sesh thanks for letting us know! I knew this change wouldn't please everyone. If we get a ground swell of support for Top New First, we will definitely reconsider.

**Comment by jerodsanto** [comment]
At this point I think we're going to leave the order how it is. However, we do have another idea brewing we think will alleviate your pain. Closing this for now, but keep your eyes peeled for more improvements!
