### ISSUE TITLE
reminder that white version exists

### ISSUE THREAD

**Issue by omidfi** [thechangelog/nightly#26]
Hello, 
I love the content but the dark theme was hard on my eyes and I was struggling to read it all the time. 

I came here and found out that a light version exists, I resubscribed again with the light version. 

**Idea**: right down there in the email, beside unsubscribe, add a small note that says there are two versions. I was so close to unsubscribing multiple times, and such a text would help me make my life easier a few months back :) 

Thanks

**Comment by jerodsanto** [comment]
Good point @omidfi! I prefer the day theme as well for this very same reason (only about 10% of subscribers are on the day theme btw).

We already have a link in the footer which you can use to switch your theme:

<img width="519" alt="2017-04-26 at 9 58 am" src="https://cloud.githubusercontent.com/assets/8212/25441243/45181f86-2a67-11e7-99e1-30cce6972a5e.png">

Do you think it'd be sufficient to change the wording there to say "Switch to [Day|Night] theme" instead of "Manage your preferences"?

**Comment by omidfi** [comment]
Thanks @jerodsanto.
Sorry seems like github didn't get my reply to your question. Great job, I think it solves the issue :)
