### ISSUE TITLE
Could be better to have metrics information below the resp. repositories.

### ISSUE THREAD

**Issue by arjunmayilvaganan** [thechangelog/nightly#27]
![screen shot 2017-04-26 at 20 12 33](https://cloud.githubusercontent.com/assets/6371303/25440321/bd55138c-2abc-11e7-8572-6f3676b11f44.png)

Metrics: 'Total Stars / New Stars / Programming Language' information.

I have purposefully left metrics of the `react-sketchapp` out the scope in the screen grab above. Once I start to scroll, Every time I'm kinda forgetting that the metric of a given repository is the one above it and hence momentarily looking below. I think, due to tradition, we expect to look for the metric below the repository and I'm surprised nobody has given this feedback before me.

My guess is that, people are either ignoring the metrics or misinterpreting the metrics (for eg., `awesome-wasm`'s metric as `react-sketchapp`'s.)

**Comment by jerodsanto** [comment]
@codyjames @adamstac how do you feel about this change?

**Comment by adamstac** [comment]
I can see how this can be better.
![nightly-stats-below](https://cloud.githubusercontent.com/assets/2933/25443573/d2e16362-2a6d-11e7-866c-24efbff429a8.png)

**Comment by jerodsanto** [comment]
My concern with metrics on the bottom is when scrolling you can end up in the same position as with metrics on top: not sure which repo they attach to (this problem is exacerbated when a repo has a super long description, which is sometimes the case).

Another minor issue I have with this solution is that Nightly is mostly about those metrics, so putting them at the bottom ever-so-slightly messes up the information architecture.

Two other options that might work well:

1. Switch the order to Name -> Metrics -> Description. That'd look like this:

<img width="601" alt="2017-05-01 at 9 31 am" src="https://cloud.githubusercontent.com/assets/8212/25582091/076e1ef4-2e51-11e7-87b6-16700e98e487.png">

2. Change the vertical alignment so the Metrics line up with the avatar instead of above it. That'd looks like this:

<img width="610" alt="2017-05-01 at 9 33 am" src="https://cloud.githubusercontent.com/assets/8212/25582143/499d9dc2-2e51-11e7-80a9-d44bf9ff5f98.png">

Thoughts on these solutions? I actually dig #2 quite a bit since it is the smallest change we could make to balance things out.

**Comment by arjunmayilvaganan** [comment]
> My concern with metrics on the bottom is when scrolling you can end up in the same position as with metrics on top: not sure which repo they attach to.

In my opinion, It is far less likely that people might be confused with, to which repo certain metrics attach to, in case the metrics are at the bottom. Because, I think displaying metrics at the bottom has been the tradition and people are used to it (Like Reactions and comments in Facebook and Likes and RTs in Twitter). Imagine the Number of likes and retweets at the top of any tweet in Twitter. It makes sense for me to read the repository name, description and then look at how popular the given project is.

But, I also like both the alternatives you've suggested. If we need emphasis on the metrics over the Repository name and description, [latter](https://cloud.githubusercontent.com/assets/8212/25582143/499d9dc2-2e51-11e7-80a9-d44bf9ff5f98.png) will work (also solves the issue of trying to figure, to which repository a given metrics attach to), while the [former](https://cloud.githubusercontent.com/assets/8212/25582091/076e1ef4-2e51-11e7-87b6-16700e98e487.png) looks aesthetically pleasing.

**Comment by jerodsanto** [comment]
I opted for the simplest change for now. Let's live with this for a bit and re-open if anyone thinks the alternative solutions are preferable.

Thanks for bringing this UX issue to our attention @arjunmayilvaganan! 💚
